version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword  # 루트 비밀번호
      MYSQL_DATABASE: my_database        # 기본 데이터베이스 이름
      MYSQL_USER: my_user                # MySQL 사용자 이름
      MYSQL_PASSWORD: mypassword        # MySQL 사용자 비밀번호
    ports:
      - "3306:3306"  # 호스트와 컨테이너의 포트 매핑
    volumes:
      - mysql_data:/var/lib/mysql  # 데이터 영속성 유지
    networks:
      - backend_network  # 네트워크 설정

volumes:
  mysql_data:  # 데이터 저장소

networks:
  backend_network:  # 네트워크 설정